### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by tirelibirefe** [aerogear/keycloak-metrics-spi#135]
### Name and Version

bitnami/keycloak:7.1.7

### What steps will reproduce the bug?

Hello,
This is my metrics configuration:

```
metrics:
  enabled: true
  service:
    ports:
      http: 9990
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.ports.http }}"
  serviceMonitor:
    enabled: true
    namespace: "monitoring"
    interval: 30s
    scrapeTimeout: ""
    labels: {}
    selector: {}
    relabelings: []
    metricRelabelings: []
    honorLabels: false
    jobLabel: ""
```

I see Keycloak can be scraped by Prometheus:

![image](https://user-images.githubusercontent.com/45227339/167664913-3b2be415-2985-4b69-b805-d7f34b38ce95.png)

I uploaded following Grafana dashboard https://grafana.com/grafana/dashboards/10441

### What is the expected behavior?

I expect to see Prometheus data can be read by Grafana.

### What do you see instead?

![image](https://user-images.githubusercontent.com/45227339/167674374-dc55a7e5-9a2e-4338-a40e-062f2654a53c.png)

...but Grafana cannot detect variables, data cannot be read, all graphs are empty:

![image](https://user-images.githubusercontent.com/45227339/167666955-1e68f40e-7e74-4214-b688-ea652de4da3c.png)

### Additional information

Could you please advise?

Thanks & Regards
