### ISSUE TITLE
No data in grafana

### ISSUE THREAD

**Issue by kgoedert** [aerogear/keycloak-metrics-spi#60]
## Description
I am following this tutorial https://quarkus.io/guides/security-keycloak-authorization to setup keycloak for a sample app. And I would like to show data in grafana

## Expected Behavior
Charts being plotted in grafana with keycloak data

## Actual Behavior
No data is shown

## Environment

* Operating system:
* OpenShift versions:
* Project Versions: 

I am able to access keycloak metrics in the browser http://localhost:8180/auth/realms/quarkus/metrics. 

The data is just not plotted in grafana.

My prometheus config is as follows:

```
  - job_name: "keycloak"
    metrics_path: /auth/realms/quarkus/metrics
    static_configs:
      - targets: ["10.1.1.79:8180"]
```
